<script setup>
import { computed, ref } from 'vue'

const lang = ref(window.location.hash.startsWith('#/fa') ? 'fa' : 'en')
const slug = ref(window.location.hash.split('/')[2] || 'introduction')
const dark = ref(localStorage.getItem('scaffolder-theme') === 'dark')
const query = ref('')

const docs = {
  en: {
    dir: 'ltr',
    nav: [['introduction','Introduction'],['installation','Installation'],['module-generator','Module Generator'],['architecture','Architecture'],['schema-generation','Schema Generation'],['command-options','Command Reference'],['swagger','Swagger / OpenAPI'],['goli','Goli / Jalali Dates'],['configuration','Configuration'],['testing','Testing'],['extending','Extending'],['troubleshooting','Troubleshooting']],
    pages: {
      introduction: ['Introduction','Laravel Scaffolder generates a production-friendly Laravel feature stack around an Eloquent model or explicit schema. It creates normal application code, so you keep full control after generation.',[['What it generates','Repository contracts and Eloquent repositories; service classes and contracts; DTOs; CRUD actions; controllers; FormRequests; API Resources; Policies; Providers and bindings; Feature Tests; OpenAPI/Swagger documentation.'],['Compatibility','PHP 8.1–8.5, Laravel 10–13, Composer 2.x.'],['Workflow','Install the package → create a model/migration or define --fields → run make:module → review generated layers → add business rules → generate Swagger when the API is ready.'],['Example','```bash\ncomposer require efati/laravel-scaffolder\nphp artisan make:model Product -m\nphp artisan make:module Product --all\n```']]],
      installation: ['Installation','Install the package in an existing Laravel application and publish files only when you need to customize them.',[['Composer','```bash\ncomposer require efati/laravel-scaffolder\n```\nPackage discovery registers Efati\\ModuleGenerator\\ModuleGeneratorServiceProvider automatically.'],['Publish base configuration','```bash\nphp artisan vendor:publish --tag=module-generator\n```\nPublishes module-generator.php, base repository/service classes, CriteriaInterface and ApiResponseHelper.'],['Publish module stubs','```bash\nphp artisan vendor:publish --tag=module-generator-stubs\n```\nUse this when you want generated classes to follow your own conventions.'],['Verify','```bash\nphp artisan list | grep -E "make:module|make:swagger|swagger:"\n```']]],
      'module-generator': ['Module Generator','make:module is the main generator. The command accepts a model/module name and a set of switches controlling each layer.',[['Basic','```bash\nphp artisan make:module Product\n```'],['API','```bash\nphp artisan make:module Product --api\n```\nAPI mode enables API controllers and FormRequests and enables Actions unless --no-actions is used.'],['Full stack','```bash\nphp artisan make:module Product --all\nphp artisan make:module Product --full\n```\nEnables controller, requests, tests, resource, provider, DTO, actions, policy and Swagger.'],['Controller subfolder','```bash\nphp artisan make:module Product --controller=Admin\n```'],['Inline schema','```bash\nphp artisan make:module Product --api \\\n  --fields="name:string:unique,price:decimal(10,2),is_active:boolean"\n```'],['Migration','```bash\nphp artisan make:module Product --from-migration=database/migrations/create_products_table.php\n```'],['Swagger only','```bash\nphp artisan make:module Product --swagger\n```\nWhen --swagger is the only generation option, normal module layers are skipped and module Swagger documentation is generated.'],['Overwrite','```bash\nphp artisan make:module Product --all --force\n```\nExisting files are skipped unless --force is supplied.']]],
      architecture: ['Generated Architecture','The package uses explicit, editable application layers rather than hiding behaviour behind a runtime abstraction.',[['Directory layout','```text\napp/\n├── Actions/\n├── DTOs/\n├── Docs/\n├── Http/Controllers/\n├── Http/Requests/\n├── Http/Resources/\n├── Policies/\n├── Providers/\n├── Repositories/Contracts/\n├── Repositories/Eloquent/\n└── Services/Contracts/\n```'],['Repository','A generated contract plus Eloquent implementation. BaseRepository supplies common persistence and Criteria support.'],['Service','Application layer above the repository. It can implement a generated service contract and is resolved through the provider binding.'],['DTO','Constructor-based typed data object generated from field metadata.'],['Actions','Create, List, Show, Update and Delete actions are available. A ListWithRelations stub is also included.'],['Controller and Request','API controllers can use actions, DTOs and resources. Store/Update FormRequests are generated from schema metadata.'],['Resource and Policy','Resources reflect inferred fields/relations. Policies are optional and enabled by --policy or full generation.'],['Provider','Generates and registers repository/service bindings. With --no-provider you must bind them yourself.']]],
      'schema-generation': ['Schema Generation','Schema metadata can come from inline --fields, the existing model, or migrations.',[['Syntax','```text\nname:string\nname:string:unique\nname:string:nullable\nuser_id:foreignId:fk=users.id\nprice:decimal(10,2)\nmetadata:json\n```'],['Modifiers','nullable, null, optional; required, notnull, not-null; unique, uniq; fk=table.column and foreign(table.column).'],['Types','string, text, integer, numeric, boolean, date, datetime, json, array, uuid, email and url are normalized by SchemaParser.'],['Relations','Fields ending in _id are foreign-key candidates. Explicit relation types include belongsTo, hasOne, hasMany and belongsToMany.'],['Precedence','--fields takes priority. Otherwise runtime model metadata and migration metadata are merged; fillable fields can constrain the final set.'],['Example','```bash\nphp artisan make:module Order --api \\\n  --fields="customer_id:foreignId:fk=users.id,number:string:unique,total:decimal(12,2),notes:text:nullable"\n```']]],
      'command-options': ['Command Reference','Complete reference for the current Artisan command surface.',[['make:module','```text\n--controller= / -c\n--api\n--requests / -r\n--tests / -t\n--no-controller / -nc\n--no-resource / -nr\n--no-dto / -nd\n--no-test / -nt\n--no-provider / -np\n--actions / --no-actions\n--policy / --no-policy\n--swagger / -sg / --no-swagger\n--all / -a\n--full / -f\n--from-migration / -fm\n--fields\n--force\n```'],['Interactions','API enables requests. API enables actions unless --no-actions is used. --swagger normally enables API mode. --all/--full enables all major layers including Policy. --controller forces controller generation.'],['swagger:generate','```bash\nphp artisan swagger:generate --output=storage/swagger-ui/swagger.json --title="My API" --version="2.0.0" --host="https://api.example.com"\n```'],['swagger:init','```bash\nphp artisan swagger:init\nphp artisan swagger:init --force\n```'],['swagger:ui','```bash\nphp artisan swagger:ui\nphp artisan swagger:ui --port=8080 --host=0.0.0.0 --refresh\n```'],['swagger:config','```bash\nphp artisan swagger:config --show\nphp artisan swagger:config --theme=dark\nphp artisan swagger:config --export-env\n```'],['make:swagger','Deprecated compatibility command. Prefer swagger:generate.']]],
      swagger: ['Swagger / OpenAPI','The package includes a JSON-based OpenAPI workflow and a standalone Swagger UI.',[['Generate','```bash\nphp artisan swagger:generate\n```\nThe generator creates an OpenAPI 3.0 specification from API routes and controller information.'],['API route detection','Routes using the api middleware or an api/ URI prefix are considered API routes. Common vendor/documentation routes are ignored.'],['Metadata','Use --title, --version, --host and --output to control the generated specification.'],['Security','The default configuration includes bearerAuth using HTTP bearer authentication with JWT as bearer format.'],['UI themes','vanilla, tailwind and dark are supported by the Swagger configuration.'],['Module annotations','```bash\nphp artisan make:module Product --swagger\n```\nUse Swagger-only generation when you need module documentation without regenerating the rest of the feature.']]],
      goli: ['Goli / Jalali Dates','Goli is the package built-in Jalali date helper with Carbon interoperability, formatting, conversion and Persian-digit support.',[['Helper','```php\nuse function goli;\n$date = goli(\'1403-01-01\');\necho $date->toGoliDateString();\n```'],['Parsing and creation','```php\nGoli::now();\nGoli::parse(\'1403-01-01\');\nGoli::parseGoli(\'۱۴۰۳-۰۱-۰۱ 12:30:00\');\nGoli::create(1403, 1, 1, 12, 30);\n```'],['Conversion','```php\nGoli::goliToGregorian(1403, 1, 1);\nGoli::gregorianToGoli(2024, 3, 20);\nGoli::isLeapGoliYear(1403);\n```'],['Formatting','```php\n$date->toGoliDateString();\n$date->toGoliDateString(true);\n$date->toGoliDateTimeString();\n$date->format(\'Y-m-d H:i:s\', true);\n$date->formatGregorian(\'Y-m-d H:i:s\');\n```'],['Eloquent cast','```php\nprotected $casts = [\n    \'scheduled_at\' => GoliDateCast::class,\n];\n```'],['HasGoliDates','```php\nuse HasGoliDates;\nprotected array $goliDates = [\'scheduled_at\'];\n```'],['Verta','Verta is deprecated since 1.0.0 and extends Goli for backward compatibility. New code should use Goli or goli().'],['Digits and human diff','```php\nGoli::persianNumbers(\'1403/01/01\');\nGoli::latinNumbers(\'۱۴۰۳/۰۱/۰۱\');\n$date->diffForHumans();\n```']]],
      configuration: ['Configuration','All generator defaults and output locations live in config/module-generator.php.',[['Namespace','```php\n\'base_namespace\' => \'App\',\n```\nCustom namespaces such as Company\\Core are supported.'],['Paths','```php\n\'repository\' => [\'eloquent\' => \'Repositories/Eloquent\', \'contracts\' => \'Repositories/Contracts\'],\n\'service\' => [\'concretes\' => \'Services\', \'contracts\' => \'Services/Contracts\'],\n\'dto\' => \'DTOs\', \'provider\' => \'Providers\',\n\'resource\' => \'Http/Resources\', \'form_request\' => \'Http/Requests\',\n\'actions\' => \'Actions\', \'docs\' => \'Docs\'\n```'],['Defaults','with_controller=true, with_form_requests=false, with_unit_test=true, with_resource=true, with_dto=true, with_provider=true, with_actions=false, controller_type=api, controller_middleware=[].'],['Swagger','Configure theme, colors, fonts, dark_mode, display, server, spec and security. Themes: vanilla, tailwind, dark.'],['Environment example','```dotenv\nSWAGGER_THEME=dark\nSWAGGER_UI_TITLE="My API"\nSWAGGER_SPEC_PATH=storage/swagger-ui\nSWAGGER_SPEC_FILENAME=swagger.json\nSWAGGER_SECURE_SPEC=true\nMODULE_GENERATOR_LOG_CHANNEL=stack\n```']]],
      testing: ['Testing','The package uses PHPUnit and Orchestra Testbench, and can generate feature tests for application modules.',[['Package tests','```bash\ncomposer install\ncomposer test\n```'],['Generated tests','```bash\nphp artisan make:module Product --tests\n```\nUse --no-test to skip them.'],['Extend them','Add factories, authentication, authorization, fixtures and domain invariants to the generated tests.'],['Example','```php\n$this->postJson(\'/api/v1/products\', [\'name\' => \'Keyboard\', \'price\' => 99.99])\n    ->assertSuccessful();\n```']]],
      extending: ['Extending & Customizing','Published stubs and base classes let the generator follow your team architecture.',[['Stubs','```bash\nphp artisan vendor:publish --tag=module-generator-stubs\n```\nEdit published module stubs instead of modifying package internals.'],['Base classes','BaseRepository, BaseRepositoryInterface, BaseService, BaseServiceInterface and CriteriaInterface are publishable.'],['Paths and defaults','Change config/module-generator.php to move generated layers or change default switches.'],['Enum helper','EnumHelperTrait provides toList(), toMap(), findByValue() and findByName() for backed enums and returns name/fa_name/code metadata.'],['Principle','Generated code belongs to the application. Treat it as a starting point and modify it normally.']]],
      troubleshooting: ['Troubleshooting','Most generation problems are deterministic and can be diagnosed from the command options and schema source.',[['Missing model','If no model exists, provide --fields or --from-migration, or create the model first.'],['Existing files','Files are skipped by default. Use --force to overwrite.'],['Invalid fields','Field names must be valid PHP identifiers and cannot be PHP reserved keywords. Duplicate inline fields are rejected.'],['No inferred fields','Use --fields when neither runtime model inspection nor migrations provide reliable metadata.'],['Provider disabled','With --no-provider you must define repository/service bindings manually.'],['Swagger empty','Verify the route is API middleware or starts with api/, is not ignored, and run swagger:generate again.'],['Deprecated command','Replace make:swagger with swagger:generate.']]]
    }
  },
  fa: {
    dir: 'rtl',
    nav: [['introduction','معرفی'],['installation','نصب'],['module-generator','سازنده ماژول'],['architecture','معماری خروجی'],['schema-generation','تولید Schema'],['command-options','مرجع Commandها'],['swagger','Swagger و OpenAPI'],['goli','Goli و تاریخ جلالی'],['configuration','تنظیمات'],['testing','تست‌ها'],['extending','گسترش و سفارشی‌سازی'],['troubleshooting','رفع مشکل']],
    pages: {
      introduction: ['معرفی','Laravel Scaffolder برای یک Model یا Schema مشخص، لایه‌های کامل یک Feature را تولید می‌کند و خروجی آن کد عادی و قابل ویرایش پروژه است.',[['امکانات','Repository و Contract، Service و Contract، DTO، CRUD Action، Controller، FormRequest، Resource، Policy، Provider، Feature Test و Swagger/OpenAPI.'],['سازگاری','PHP 8.1 تا 8.5، Laravel 10 تا 13 و Composer 2.x.'],['Workflow','نصب → ساخت Model/Migration یا تعریف --fields → اجرای make:module → بررسی خروجی → افزودن Business Logic → تولید Swagger.'],['نمونه','```bash\ncomposer require efati/laravel-scaffolder\nphp artisan make:model Product -m\nphp artisan make:module Product --all\n```']]],
      installation: ['نصب','پکیج را با Composer نصب کنید و در صورت نیاز Configuration و Stubها را Publish کنید.',[['Composer','```bash\ncomposer require efati/laravel-scaffolder\n```'],['Publish Configuration','```bash\nphp artisan vendor:publish --tag=module-generator\n```'],['Publish Stubها','```bash\nphp artisan vendor:publish --tag=module-generator-stubs\n```'],['بررسی Commandها','```bash\nphp artisan list | grep -E "make:module|make:swagger|swagger:"\n```']]],
      'module-generator': ['سازنده ماژول','make:module Command اصلی Generator است.',[['ساخت پایه','```bash\nphp artisan make:module Product\n```'],['API','```bash\nphp artisan make:module Product --api\n```\nAPI باعث فعال‌شدن Controller API و Request می‌شود و Actionها را نیز فعال می‌کند مگر اینکه --no-actions بدهید.'],['Full Stack','```bash\nphp artisan make:module Product --all\nphp artisan make:module Product --full\n```'],['Controller Subfolder','```bash\nphp artisan make:module Product --controller=Admin\n```'],['Schema دستی','```bash\nphp artisan make:module Product --api \\\n  --fields="name:string:unique,price:decimal(10,2),is_active:boolean"\n```'],['Migration','```bash\nphp artisan make:module Product --from-migration=database/migrations/create_products_table.php\n```'],['Swagger Only','```bash\nphp artisan make:module Product --swagger\n```'],['Force','```bash\nphp artisan make:module Product --all --force\n```']]],
      architecture: ['معماری خروجی','خروجی پکیج از لایه‌های واضح و قابل ویرایش تشکیل می‌شود.',[['ساختار','```text\napp/\n├── Actions/\n├── DTOs/\n├── Docs/\n├── Http/Controllers/\n├── Http/Requests/\n├── Http/Resources/\n├── Policies/\n├── Providers/\n├── Repositories/Contracts/\n├── Repositories/Eloquent/\n└── Services/Contracts/\n```'],['Repository','Contract و Eloquent Repository تولید می‌شود و BaseRepository امکانات پایه Persistence و Criteria را فراهم می‌کند.'],['Service','لایه بالاتر از Repository است و در صورت فعال‌بودن Provider با Contract خود Bind می‌شود.'],['DTO','Object تایپ‌شده بر اساس Fieldهای Schema تولید می‌شود.'],['Action','Create، List، Show، Update و Delete و Stub مربوط به ListWithRelations وجود دارد.'],['Controller و Request','Controller API می‌تواند از Action، DTO و Resource استفاده کند و Store/Update Request تولید می‌شود.'],['Resource و Policy','Resource از Field و Relation ساخته می‌شود و Policy اختیاری است.'],['Provider','Bindingهای Repository و Service را ثبت می‌کند؛ با --no-provider باید دستی Bind کنید.']]],
      'schema-generation': ['تولید Schema','Metadata می‌تواند از --fields، Model یا Migration به دست بیاید.',[['Syntax','```text\nname:string\nname:string:unique\nname:string:nullable\nuser_id:foreignId:fk=users.id\nprice:decimal(10,2)\nmetadata:json\n```'],['Modifierها','nullable، required، unique، fk=table.column و foreign(table.column).'],['Typeها','string، text، integer، numeric، boolean، date، datetime، json، array، uuid، email و url.'],['Relation','Fieldهای _id کاندید Foreign Key هستند و Relationهای belongsTo، hasOne، hasMany و belongsToMany پشتیبانی می‌شوند.'],['اولویت','--fields اولویت دارد، سپس اطلاعات Model و Migration ترکیب می‌شوند و fillable می‌تواند مجموعه نهایی را محدود کند.'],['مثال','```bash\nphp artisan make:module Order --api \\\n  --fields="customer_id:foreignId:fk=users.id,number:string:unique,total:decimal(12,2),notes:text:nullable"\n```']]],
      'command-options': ['مرجع Commandها','مرجع گزینه‌های make:module و Commandهای Swagger.',[['make:module','```text\n--controller= / -c\n--api\n--requests / -r\n--tests / -t\n--no-controller / -nc\n--no-resource / -nr\n--no-dto / -nd\n--no-test / -nt\n--no-provider / -np\n--actions / --no-actions\n--policy / --no-policy\n--swagger / -sg / --no-swagger\n--all / -a\n--full / -f\n--from-migration / -fm\n--fields\n--force\n```'],['تعامل گزینه‌ها','API Request را فعال می‌کند. API Action را فعال می‌کند مگر --no-actions. --swagger معمولاً API را فعال می‌کند. --all/--full تمام لایه‌ها را فعال می‌کنند.'],['swagger:generate','```bash\nphp artisan swagger:generate --output=storage/swagger-ui/swagger.json --title="My API" --version="2.0.0" --host="https://api.example.com"\n```'],['swagger:init','```bash\nphp artisan swagger:init\nphp artisan swagger:init --force\n```'],['swagger:ui','```bash\nphp artisan swagger:ui --port=8080 --host=0.0.0.0 --refresh\n```'],['swagger:config','```bash\nphp artisan swagger:config --show\nphp artisan swagger:config --theme=dark\n```'],['make:swagger','Deprecated است. از swagger:generate استفاده کنید.']]],
      swagger: ['Swagger و OpenAPI','پکیج Workflow کامل OpenAPI JSON و Swagger UI مستقل دارد.',[['تولید','```bash\nphp artisan swagger:generate\n```'],['تشخیص Route','Routeهای api middleware یا URI با api/ در نظر گرفته می‌شوند و Routeهای vendor/documentation حذف می‌شوند.'],['Metadata','با --title، --version، --host و --output خروجی را کنترل کنید.'],['Security','bearerAuth با HTTP bearer و فرمت JWT در Configuration پیش‌فرض وجود دارد.'],['Theme','vanilla، tailwind و dark.'],['Swagger Module','```bash\nphp artisan make:module Product --swagger\n```']]],
      goli: ['Goli و تاریخ جلالی','Goli ابزار داخلی پکیج برای تاریخ جلالی، تبدیل با Carbon، Format و ارقام فارسی است.',[['Helper','```php\nuse function goli;\n$date = goli(\'1403-01-01\');\necho $date->toGoliDateString();\n```'],['Parse و Create','```php\nGoli::now();\nGoli::parse(\'1403-01-01\');\nGoli::parseGoli(\'۱۴۰۳-۰۱-۰۱ 12:30:00\');\nGoli::create(1403, 1, 1, 12, 30);\n```'],['Conversion','```php\nGoli::goliToGregorian(1403, 1, 1);\nGoli::gregorianToGoli(2024, 3, 20);\nGoli::isLeapGoliYear(1403);\n```'],['Format','```php\n$date->toGoliDateString();\n$date->toGoliDateString(true);\n$date->toGoliDateTimeString();\n$date->formatGregorian(\'Y-m-d H:i:s\');\n```'],['Eloquent Cast','```php\nprotected $casts = [\'scheduled_at\' => GoliDateCast::class];\n```'],['HasGoliDates','```php\nuse HasGoliDates;\nprotected array $goliDates = [\'scheduled_at\'];\n```'],['Verta','Verta از نسخه 1.0.0 Deprecated است و برای سازگاری روی Goli قرار دارد.'],['اعداد و اختلاف','```php\nGoli::persianNumbers(\'1403/01/01\');\nGoli::latinNumbers(\'۱۴۰۳/۰۱/۰۱\');\n$date->diffForHumans();\n```']]],
      configuration: ['تنظیمات','تنظیمات اصلی در config/module-generator.php قرار دارد.',[['Namespace','```php\n\'base_namespace\' => \'App\',\n```'],['Paths','Repository، Service، DTO، Provider، Controller، Resource، Request، Action و Docs قابل جابه‌جایی هستند.'],['Defaults','with_controller=true، with_form_requests=false، with_unit_test=true، with_resource=true، with_dto=true، with_provider=true، with_actions=false و controller_type=api.'],['Swagger','theme، colors، fonts، dark_mode، display، server، spec و security قابل تنظیم هستند.'],['Environment','```dotenv\nSWAGGER_THEME=dark\nSWAGGER_UI_TITLE="My API"\nSWAGGER_SPEC_PATH=storage/swagger-ui\nSWAGGER_SPEC_FILENAME=swagger.json\nSWAGGER_SECURE_SPEC=true\nMODULE_GENERATOR_LOG_CHANNEL=stack\n```']]],
      testing: ['تست‌ها','پکیج از PHPUnit و Orchestra Testbench استفاده می‌کند و می‌تواند Feature Test تولید کند.',[['تست پکیج','```bash\ncomposer install\ncomposer test\n```'],['تست Module','```bash\nphp artisan make:module Product --tests\n```'],['گسترش','Factory، Authentication، Authorization و Business Invariantها را به Testهای تولیدشده اضافه کنید.'],['مثال','```php\n$this->postJson(\'/api/v1/products\', [\'name\' => \'Keyboard\', \'price\' => 99.99])\n    ->assertSuccessful();\n```']]],
      extending: ['گسترش و سفارشی‌سازی','Stub و Base Classهای قابل Publish اجازه می‌دهند Generator با معماری تیم هماهنگ شود.',[['Stubها','```bash\nphp artisan vendor:publish --tag=module-generator-stubs\n```'],['Base Classها','BaseRepository، BaseRepositoryInterface، BaseService، BaseServiceInterface و CriteriaInterface قابل Publish هستند.'],['Paths و Defaults','config/module-generator.php را برای تغییر مسیر و Defaultها ویرایش کنید.'],['EnumHelperTrait','متدهای toList، toMap، findByValue و findByName را برای Backed Enum فراهم می‌کند و name/fa_name/code برمی‌گرداند.'],['اصل مهم','کد تولیدشده متعلق به پروژه است و باید بعد از Generation مطابق نیاز تغییر کند.']]],
      troubleshooting: ['رفع مشکل','مشکلات Generator معمولاً از Schema یا گزینه‌های Command قابل تشخیص هستند.',[['Model پیدا نشد','Model را بسازید یا --fields/--from-migration بدهید.'],['فایل موجود','بدون --force فایل موجود Skip می‌شود.'],['Field نامعتبر','نام باید PHP identifier معتبر باشد و Reserved Keyword نباشد. Field تکراری نیز رد می‌شود.'],['Field تشخیص داده نمی‌شود','برای خروجی قطعی از --fields استفاده کنید.'],['Provider خاموش','با --no-provider باید Bindingها را دستی ثبت کنید.'],['Swagger خالی','API middleware یا api/ بودن URI را بررسی کنید و Routeهای ignored را نیز در نظر بگیرید.'],['Deprecated','make:swagger را با swagger:generate جایگزین کنید.']]]
    }
  }
}

const locale = computed(() => docs[lang.value])
const page = computed(() => locale.value.pages[slug.value] || locale.value.pages.introduction)
const nav = computed(() => locale.value.nav.filter(([, title]) => title.toLowerCase().includes(query.value.toLowerCase())))
const setRoute = (next) => { slug.value = next; window.location.hash = `#/${lang.value}/${next}`; window.scrollTo({top:0,behavior:'smooth'}) }
const switchLang = () => { lang.value = lang.value === 'en' ? 'fa' : 'en'; window.location.hash = `#/${lang.value}/${slug.value}` }
const toggleTheme = () => { dark.value = !dark.value; localStorage.setItem('scaffolder-theme', dark.value ? 'dark' : 'light') }
const copy = (text) => navigator.clipboard?.writeText(text)
const render = (text) => text.replace(/```(\w+)?\n([\s\S]*?)```/g, (_, lang, body) => `<div class="code"><div class="codebar"><span>${lang || 'text'}</span><button data-copy="${encodeURIComponent(body.trim())}">Copy</button></div><pre>${body.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}</pre></div>`).replace(/\n/g,'<br>')
const onContentClick = (e) => { const b = e.target.closest('[data-copy]'); if (b) copy(decodeURIComponent(b.dataset.copy)) }
</script>

<template>
  <div :dir="locale.dir" :class="['app', { dark }]">
    <header class="topbar"><div class="topbar-inner">
      <button class="brand" @click="setRoute('introduction')"><span class="logo">L</span><span><b>Laravel Scaffolder</b><small>Documentation</small></span></button>
      <div class="actions"><a href="https://github.com/AfshinEfati/Laravel-Scaffolder" target="_blank">GitHub</a><button @click="toggleTheme">{{ dark ? '☀' : '◐' }}</button><button @click="switchLang">{{ lang === 'en' ? 'فارسی' : 'English' }}</button></div>
    </div></header>
    <div class="layout">
      <aside class="sidebar"><div class="side-inner"><div class="search"><span>⌕</span><input v-model="query" :placeholder="lang === 'en' ? 'Search documentation...' : 'جست‌وجوی مستندات...'" /></div><nav><button v-for="[s,t] in nav" :key="s" :class="{active:s===slug}" @click="setRoute(s)">{{ t }}</button></nav><div class="side-foot"><span>PHP 8.1–8.5</span><span>Laravel 10–13</span></div></div></aside>
      <main class="main"><div class="hero"><span class="eyebrow">Laravel Scaffolder</span><h1>{{ page[0] }}</h1><p>{{ page[1] }}</p></div><article class="doc" @click="onContentClick"><section v-for="([title, body], i) in page[2]" :key="i"><h2>{{ title }}</h2><div class="body" v-html="render(body)"></div></section></article><footer><a href="https://github.com/AfshinEfati/Laravel-Scaffolder">Laravel Scaffolder on GitHub</a><span>MIT License</span></footer></main>
    </div>
  </div>
</template>
